using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class InputManager : MonoBehaviour
{
    //Ref: https://www.youtube.com/watch?v=yRI44aYLDQs
    public static InputManager inst;
    //Action map on the c# script generated by the input system
    private InputSystem.CharacterActions characterMap;
    private void Awake() {
        //Making sure there will be only one InputManager
        if(!inst){
            inst = this;
            DontDestroyOnLoad(gameObject);
        }
        else Destroy(gameObject);

        characterMap = new InputSystem().Character;
    }
    private void OnEnable(){
        characterMap.Enable();
    }
    private void OnDisable() {
        characterMap.Disable();
    }
    //Getting the WASD keys
    public Vector3 MovementInput(){
        return new Vector3(characterMap.Movement.ReadValue<Vector2>().x,0,
                            characterMap.Movement.ReadValue<Vector2>().y);
    }
    //Getting the Space key
    public bool JumpInput(){
        return characterMap.Jump.triggered;
    }
    //Getting the Space key when is pressed
    public bool JumpPressed(){
        return characterMap.Jump.IsPressed();
    }
    //Getting the Left-Shift key
    public bool RunInput(){
        return characterMap.Run.IsPressed();
    }
    public Vector2 MouseDeltaInput(){
        return characterMap.Mouse.ReadValue<Vector2>();
    }
}
